Models/Cliente.cs
namespace tallerCrud.Models
{
    public class Cliente
    {
        public int Id { get; set; }
        public int Cedula { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int Tel { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace tallerCrud.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Producto.cs
namespace tallerCrud.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public int Cantidad { get; set; }
    }
}

Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using tallerCrud.Data;
using tallerCrud.Models;
using Microsoft.EntityFrameworkCore;

namespace tallerCrud.Controllers
{
    public class ClientesController : Controller
    {
        private readonly AplicationDbContext _context;
        public ClientesController(AplicationDbContext context)
        {
            _context = context;
        }
        //public IActionResult Index()
        //{
        //    IEnumerable<Libro> ListLibros = _context.Libro;
        //    return View(ListLibros);
        //}

        public async Task<IActionResult> Index(int buscar)
        {
            var clientes = from cliente in _context.Cliente select cliente;

            if (buscar != 0 && buscar > 0)
            {
                clientes = clientes.Where(a => a.Cedula == buscar);
            }
            return View(await clientes.ToListAsync());
        }

        public IActionResult Create(Cliente cliente)
        {
            //validar el modelo
            if (ModelState.IsValid)
            {
                _context.Cliente.Add(cliente);
                _context.SaveChanges();  /*guardan los cambiops*/

                TempData["Mensaje"] = "cliente creado exitosamente";

                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cliente = _context.Cliente.Find(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);


        }


        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {
            //validar el modelo
            if (ModelState.IsValid)
            {
                _context.Cliente.Update(cliente);
                _context.SaveChanges();  /*guardan los cambiops*/

                TempData["Mensaje"] = "Cliente actulizado exitosamente";

                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cliente = _context.Cliente.Find(id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteCliente(int? id)
        {
            var cliente = _context.Cliente.Find(id);
            if (cliente == null)
            {
                return NotFound();
            }

            _context.Cliente.Remove(cliente);
            _context.SaveChanges();

            TempData["Mensaje"] = "Cliente eliminado exitosamente";
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tallerCrud.Models;

namespace tallerCrud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using tallerCrud.Data;
using tallerCrud.Models;
using Microsoft.EntityFrameworkCore;


namespace tallerCrud.Controllers
{
    public class ProductosController : Controller
    {
        private readonly AplicationDbContext _context;
        public ProductosController(AplicationDbContext context)
        {
            _context = context;
        }
        //public IActionResult Index()
        //{
        //    IEnumerable<Libro> ListLibros = _context.Libro;
        //    return View(ListLibros);
        //}

        public async Task<IActionResult> Index(int buscar)
        {
            var productos = from producto in _context.Producto select producto;

            if (buscar != 0 && buscar > 0)
            {
                productos = productos.Where(a => a.Codigo== buscar);
            }
            return View(await productos.ToListAsync());
        }

        public IActionResult Create(Producto producto)
        {
            //validar el modelo
            if (ModelState.IsValid)
            {
                _context.Producto.Add(producto);
                _context.SaveChanges();  /*guardan los cambiops*/

                TempData["Mensaje"] = "Producto creado exitosamente";

                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Edit(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var producto = _context.Producto.Find(id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);


        }


        [HttpPost]
        public IActionResult Edit(Producto producto)
        {
            //validar el modelo
            if (ModelState.IsValid)
            {
                _context.Producto.Update(producto);
                _context.SaveChanges();  /*guardan los cambiops*/

                TempData["Mensaje"] = "Producto actulizado exitosamente";

                return RedirectToAction("Index");
            }
            return View();
        }


        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var producto = _context.Producto.Find(id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);


        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public IActionResult DeleteProducto(int? id)
        {
            var producto = _context.Producto.Find(id);
            if (producto == null)
            {
                return NotFound();
            }

            _context.Producto.Remove(producto);
            _context.SaveChanges();

            TempData["Mensaje"] = "Producto eliminado exitosamente";
            return RedirectToAction("Index");
        }
    }
}

Views/Clientes/Create.cshtml
@model tallerCrud.Models.Cliente;
@{
    ViewData["Title"] = "Crear nuevo registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear nuevo Cliente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">

@*                para validar modelo por parte del servidor*@
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Cedula" class="control.label"></label>
                    <input asp-for="Cedula" class="form-control" />
@*                    validar por parte del cliente*@
                    <span asp-validation-for="Cedula" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control.label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Direccion" class="control.label"></label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Tel" class="control.label"></label>
                    <input asp-for="Tel" class="form-control" />
                    <span asp-validation-for="Tel" class="text-danger"></span>

                </div>
                <br/>
                <div class="form-group">
                    <input type="submit" value="Crear Cliente" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Views/Clientes/Delete.cshtml
@model tallerCrud.Models.Cliente;
@{
    ViewData["Title"] = "Eliminar Cliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Eliminar cliente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteCliente">

                <input type="hidden" asp-for="Id"/>

                @*                para validar modelo por parte del servidor*@
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Cedula" class="control.label"></label>
                    <input asp-for="Cedula" class="form-control" disabled/>
                    @*                    validar por parte del cliente*@
                    <span asp-validation-for="Cedula" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control.label"></label>
                    <input asp-for="Nombre" class="form-control" disabled/>
                    <span asp-validation-for="Nombre" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Direccion" class="control.label"></label>
                    <input asp-for="Direccion" class="form-control" disabled />
                    <span asp-validation-for="Direccion" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Tel" class="control.label"></label>
                    <input asp-for="Tel" class="form-control" disabled/>
                    <span asp-validation-for="Tel" class="text-danger"></span>

                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Eliminar Cliente" class="btn btn-danger" />
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Clientes/Edit.cshtml
@model tallerCrud.Models.Cliente;
@{
    ViewData["Title"] = "Editar Cliente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Editar Cliente</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Edit">

                @*                para validar modelo por parte del servidor*@
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Cedula" class="control.label"></label>
                    <input asp-for="Cedula" class="form-control" />
                    @*                    validar por parte del cliente*@
                    <span asp-validation-for="Cedula" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control.label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Direccion" class="control.label"></label>
                    <input asp-for="Direccion" class="form-control" />
                    <span asp-validation-for="Direccion" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Tel" class="control.label"></label>
                    <input asp-for="Tel" class="form-control" />
                    <span asp-validation-for="Tel" class="text-danger"></span>

                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Editar Cliente" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Clientes/Index.cshtml
@model IEnumerable<tallerCrud.Models.Cliente>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Clientes</h1>

@*creacion de tabla con boostrap*@


<div class="container">

    @*mostrar un el mensaje de return de Create*@
    @if (TempData["Mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["Mensaje"]
            <button type="button" class="close" date-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }


    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de clientes</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Clientes">Agregar Cliente</a>
        </div>

        <form>
            <p>
                Buscar: <input type="text" name="buscar" class="form-text" />
                <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
            </p>
        </form>
    </div>

    <div class="row">
        @*    validar si hay registros*@
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(a=>a.Id)</td>
                        <td>@Html.DisplayNameFor(a=>a.Cedula)</td>
                        <td>@Html.DisplayNameFor(a=>a.Nombre)</td>
                        <td>@Html.DisplayNameFor(a=>a.Direccion)</td>
                        <td>@Html.DisplayNameFor(a=>a.Tel)</td>
                    </tr>
                </thead>
                <tbody>
                    @*para recorrer los registros*@
                    @foreach (var i in Model)
                    {
                        <tr>
                            <td>@i.Id</td>
                            <td>@i.Cedula</td>
                            <td>@i.Nombre</td>
                            <td>@i.Direccion</td>
                            <td>@i.Tel</td>
                            <td>
                                <a asp-controller="Clientes" asp-action="Edit" asp-route-id="@i.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Clientes" asp-action="Delete" asp-route-id="@i.Id" class="btn btn-danger">Eliminar</a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No Existe el registro</p>
        }

    </div>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Productos/Create.cshtml
@model tallerCrud.Models.Producto;
@{
    ViewData["Title"] = "Crear nuevo registro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>Crear nuevo Producto</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="Create">

@*                para validar modelo por parte del servidor*@
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Codigo" class="control.label"></label>
                    <input asp-for="Codigo" class="form-control" />
@*                    validar por parte del cliente*@
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control.label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Precio" class="control.label"></label>
                    <input asp-for="Precio" class="form-control" />
                    <span asp-validation-for="Precio" class="text-danger"></span>

                </div>
                <div class="form-group">
                    <label asp-for="Cantidad" class="control.label"></label>
                    <input asp-for="Cantidad" class="form-control" />
                    <span asp-validation-for="Cantidad" class="text-danger"></span>

                </div>
                <br/>
                <div class="form-group">
                    <input type="submit" value="Crear Producto" class="btn btn-primary" />
                </div>

            </form>
        </div>
    </div>

</div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
}

Views/Productos/Index.cshtml
@model IEnumerable<tallerCrud.Models.Producto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Productos</h1>

@*creacion de tabla con boostrap*@


<div class="container">

    @*mostrar un el mensaje de return de Create*@
    @if (TempData["Mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["Mensaje"]
            <button type="button" class="close" date-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }


    <div class="row">
        <div class="col-sm-6">
            <h3>Lista de productos</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-action="Create" asp-controller="Productos">Agregar Producto</a>
        </div>

        <form>
            <p>
                Buscar: <input type="text" name="buscar" class="form-text" />
                <input type="submit" value="Buscar" class="btn btn-sm btn-dark" />
            </p>
        </form>
    </div>

    <div class="row">
        @*    validar si hay registros*@
        @if (Model.Count() > 0)
        {
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(a=>a.Id)</td>
                        <td>@Html.DisplayNameFor(a=>a.Codigo)</td>
                        <td>@Html.DisplayNameFor(a=>a.Nombre)</td>
                        <td>@Html.DisplayNameFor(a=>a.Precio)</td>
                        <td>@Html.DisplayNameFor(a=>a.Cantidad)</td>
                    </tr>
                </thead>
                <tbody>
                    @*para recorrer los registros*@
                    @foreach (var i in Model)
                    {
                        <tr>
                            <td>@i.Id</td>
                            <td>@i.Codigo</td>
                            <td>@i.Nombre</td>
                            <td>@i.Precio</td>
                            <td>@i.Cantidad</td>
                            <td>
                                <a asp-controller="Productos" asp-action="Edit" asp-route-id="@i.Id" class="btn btn-warning">Editar</a>
                                <a asp-controller="Productos" asp-action="Delete" asp-route-id="@i.Id" class="btn btn-danger">Eliminar</a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No Existe el registro</p>
        }

    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tallerCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tallerCrud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tallerCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - tallerCrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>